treasure-data/td-ios-sdk

Rakefile
Make it possible to install shared libraries and header files without CocoaPods
=> Add `rake framework` task

TreasureDataExample/TreasureDataExample/AppDelegate.m, TreasureDataExampleSwift/TreasureDataExampleSwift/AppDelegate.swift
https://in.ybi.idcfcloud.net/ is the new endpoint URL of Mobile SDK Backend.
=> Use new YBI URLs

README.md
=> Just fix typos.

Podfile, TreasureData.xcodeproj/project.pbxproj, TreasureData/Constants.h, TreasureData/TDUtils.h, TreasureData/TDUtils.m, TreasureData/TreasureData.h, TreasureData/TreasureData.m, TreasureDataExample/TreasureDataExample.xcodeproj/project.pbxproj, TreasureDataExample/TreasureDataExample/AppDelegate.m, TreasureDataTests/TreasureDataTests.m
Remake from https://github.com/treasure-data/td-ios-sdk/pull/35 without any refactors. Changes are kept minimal both in the API and the implementation.
=> Automated event tracking

CHANGELOG.md, Podfile, README.md, TreasureData-iOS-SDK.podspec, TreasureData/TDClient.m, TreasureData/TreasureData.h
Along with some documentation improvements.
=> 0.1.27 Release

TreasureData/TreasureData.h, TreasureData/TreasureData.m
=> Extract common callbacks' type definitions, along with explicit parameter names

CHANGELOG.md, README.md, TreasureData-iOS-SDK.podspec, TreasureData/TDClient.m
Also adapt semantic versioning scheme
=> Prep for release 0.2.0

README.md, TreasureData/TreasureData.h, TreasureDataExample/TreasureDataExample/Base.lproj/Main.storyboard, TreasureDataExampleSwift/TreasureDataExampleSwift/ViewController.swift, TreasureDataTests/IntegrationTests.swift
=> Update fetchUserSegments signature

README.md
Update list of iOS versions test coverage to include iOS 8 and 9 in README
=> Update list of iOS versions test coverage to include iOS 8 and 9

.circleci/config.yml, README.md, TreasureDataExample/TreasureDataExample/TreasureDataExample.m
- Add test coverage for iOS 13
- Update README.md to support iOS 13
=> Update README.md to support iOS 13

CHANGELOG.md, README.md, TreasureData-iOS-SDK.podspec, TreasureData/TDClient.m
* Add documentation to support AP02 region
* Add API `getUUID` to get `td_uuid`
=> Release 0.5.0

README.md, TreasureData/TDClient.m
MD5 hash are proven to be vulnerable to collision attacks. This PR is to replace it with SHA256
=> Replace MD5 with SHA256

TreasureData/TreasureData.m, TreasureDataTests/IntegrationTests.swift
- Remove unused math import
- Better logic to test for TD_IOS_APP_OPEN event to prevent flaky test
=> Remove math import

CHANGELOG.md, README.md, TreasureData-iOS-SDK.podspec, TreasureData/TDClient.m
* Remove unused math.h import in TreasureData.m file
=> Release 0.6.1

.circleci/config.yml
Update CircleCI to test for iOS 13.6
=> Update CircleCI to test for iOS 13.6

README.md, TreasureData/TreasureData.h, TreasureData/TreasureData.m, TreasureDataExample/TreasureDataExample.xcodeproj/project.pbxproj, TreasureDataExample/TreasureDataExample/Base.lproj/Main.storyboard, TreasureDataExample/TreasureDataExample/ViewController.h, TreasureDataExample/TreasureDataExample/ViewController.m, TreasureDataTests/TreasureDataTests.m
Implementation of Default values feature for td-ios-sdk. Default value is value that will be automatically added to an event when that event is added to the specified table and database of that default value.
With this feature, SDK users can set default values for events targeting:
- Any tables
- Tables with specific name
- All tables in database with a specific name
- Specific table in a specific database
- SDK users only need to write one method call to add default values to events, compared to previously they would have to remember to add that value whenever adding new events.
- Default values also affect custom events which previously not possible for SDK users to add new customized column. This will allow SDK user to implement feature such as tracking user session themself.
=> Default values

CHANGELOG.md, README.md, TreasureData-iOS-SDK.podspec, TreasureData/TDClient.m
Change log:
- New default values feature
- New resetSessionId API
=> Release 0.7.0

CHANGELOG.md, README.md, TreasureData-iOS-SDK.podspec, TreasureData/TDClient.m
=> Release 0.8.0

TreasureData/NSString+Helpers.h, TreasureData/TreasureData.h
Fixing some Xcode compile time warnings
=> Fix compile time warnings in Xcode

.circleci/config.yml
=> Run tests for iOS 14.5

TreasureData/TreasureData.h
Add reference to AP03 endpoint in doc comment
=> Add reference to AP03 endpoint in doc comment

CHANGELOG.md, README.md, TreasureData-iOS-SDK.podspec, TreasureData/TDClient.m, TreasureDataExample/Podfile
* Fix using wrong version of KeenClientTD (should be 3.3.0).
=> Release 0.8.1

.github/workflows/deploy-docs.yaml
This adds a github action script to auto deploy the docs site on changes to the master branch source files.
=> [CLT-1756] auto deploy docs site

.circleci/config.yml
- Add CI job for iOS 16
- Update other CI jobs to the latest possible macos executor.
=> Update Circle Ci Config

CHANGELOG.md, Package.swift, README.md, TreasureData-iOS-SDK.podspec, TreasureData/TDClient.m
-  Add support for Ingest API and Ingest format
-  Event collector and keen format are no longer supported
-  New intialization APIs with removed initWithEndpoint: API
=> Release 1.0.0

CHANGELOG.md, Package.swift, Podfile, Podfile.lock, README.md, TreasureData-iOS-SDK.podspec, TreasureData/TDClient.m, TreasureDataExample/Podfile
Changelog:
* Update KeenClient-iOS to support max number of event to upload per request. Default to 400 events per request.
=> Release 1.0.1

.circleci/config.yml
=> CLT-1962 Fix ios 17 pod install fail

CHANGELOG.md, Package.swift, Podfile, Podfile.lock, README.md, TreasureData-iOS-SDK.podspec, TreasureData/TDClient.m
Changelog:
* Support privacy manifest file
=> Release 1.1.0

CHANGELOG.md, README.md, TreasureData-iOS-SDK.podspec, TreasureData/TDClient.m
Changelog:
* Add NSPrivacyAccessedAPIType to Privacy manifest
* Update KeenClientTD to 4.1.1
* Update GZIP to 1.3.2
=> Release 1.1.1

README.md
Add a breaking change doc regarding td_ip in README
=> README Auto tracking of client id by adding `td_ip` field is no longer supported

CHANGELOG.md, README.md, TreasureData-iOS-SDK.podspec, TreasureData/TDClient.m
Changelog:
- New APIs enableAutoTrackingIP and disableAutoTrackingIP to track device’s IP in td_ip column
=> Release 1.2.0

CHANGELOG.md, README.md, TreasureData-iOS-SDK.podspec, TreasureData/TDClient.m
Changelog:
- Change a couple of internal headers name
- No change in public APIs or behavior
=> Release 1.2.1
